version: '3'

services:

  api:
    labels:
      shipyard.before: 'rake db:create; rake db:migrate'
    build: 'api'
    environment:
      MTA_API_KEY: ${MTA_API_KEY}
      POSTGRES_USER: 'trains'
      POSTGRES_PASSWORD: 'trains'
    depends_on:
      - postgres
    volumes:
      - ./api:/srv
    ports:
      - '3001:3001'

  client:
    labels:
      shipyard.route: '/'
    build: 'client'
    volumes:
      - ./client/src:/srv/src
    ports:
      - '3000:3000'

  postgres:
    image: 'postgres:9.6-alpine'
    environment:
      POSTGRES_USER: 'trains'
      POSTGRES_PASSWORD: 'trains'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432'

volumes:
  postgres:

