export const RECEIVE_TRAINS = 'RECEIVE_TRAINS';
export const RECEIVE_DIRECTION = 'RECEIVE_DIRECTION';

export const RECEIVE_STATIONS = 'RECEIVE_STATIONS';
export const SELECT_STATION = 'SELECT_STATION';
